[project]
name = "extract-dust"
version = "0.1.3"
description = "Удаляет пыль из данных коэффициентов деполяризации и эффективности флуоресценции"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
]
